About us branch
HotSoupRepos/HotSoup-frontend pull request #13
Opened 2022-07-21 03:56 UTC by ariellekatherine92

made about us branch

2022-07-21 04:10 UTC, lindentree requested changes

2022-07-21 04:10 UTC, lindentree commented on src/screens/index.tsx
> +export { Home, MapList };
please import/export AboutUs here

2022-07-21 04:17 UTC, ariellekatherine92 commented on src/screens/index.tsx
> +export { Home, MapList };
all set sir :)

2022-07-26 00:05 UTC, HotSoupRepos commented
I'm closing this so we can merge in @KoffiKC PR when it is ready :) Thanks!!

2022-07-26 00:05 UTC, closed without merging