Unit test
HotSoupRepos/HotSoup-frontend pull request #21
Opened 2022-08-10 19:45 UTC by chirani

### Added two unit tests that check for the number of children in _LocationList_ component depending on the _locations_  prop.

2022-08-10 23:04 UTC, Dan-Y-Ko commented
The only input I have is I recommend using React Native Testing Library.

2022-08-11 00:02 UTC, lindentree commented
> 

Out of scope for this ticket

2022-08-11 23:16 UTC, lindentree requested changes
Please rename the test folder to ```__tests__```

2022-08-11 23:35 UTC, lindentree commented on src/test/LocationList.test.js
> +  let Location1 = [
const instead of let, and please make the mock data more realistic, eg proper lat/long values

2022-08-11 23:38 UTC, lindentree requested changes

2022-08-11 23:38 UTC, lindentree commented on src/test/LocationList.test.js
> +  let Location1 = [
should be const mockLocations, and please make the mock data more realistic, eg actual lat/long values.

2022-08-12 07:02 UTC, lindentree commented on src/test/LocationList.test.js
> +  let Location1 = [
Other than the above changes, very nice work.

2022-08-16 19:49 UTC, lindentree reviewed
Please change the order and naming of the test cases: singular should come first: const mockLocation, const mockLocations; do not use numbers to distinguish test cases unless they are of the same type - ie you have multiple mockLocations arrays with multiple items

2022-08-16 20:54 UTC, lindentree approved these changes

2022-08-16 20:57 UTC, rweitzman approved these changes

2022-08-16 20:57 UTC, merged